info:
  app:
    name: 管理后台
    description: 管理后台
    version: 1.0.0

# spring 应用
spring:
  application:
    name: shop-server
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cuteJ_shop?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&useUnicode=false&rewriteBatchedStatements=true&autoReconnect=true&useInformationSchema=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari-pool
      connection-timeout: 60000
      minimum-idle: 10
      maximum-pool-size: 20
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# 服务器配置
server:
  port: 8300
  undertow:
    accesslog:
      enabled: false
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
  error:
    include-stacktrace: always
  session:
    timeout: 1800
  context-path: /shop
shiro:
  userNativeSessionManager: true
  # Fix session invalid on 404
  sessionManager:
    cookie:
      name: ssid

# 日志配置
logging:
  path: logs/
  file: shop-server.log

# 安全配置
app:
#  oss:
#    access-key-id: 1
#    secret-access-key: 1
#    endpoint: 1
#    domainUrl: 1
#    default-bucket: 1
  cors:
    allowOrigin: http://localhost:9527,http://shop-web-mgt.onlythinking.com
    allowMethods: POST, GET, PUT, OPTIONS, DELETE
    allowHeaders: x-prototype-version,x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, x-auth-token
    allowCredentials: true
  httpclient:
    http:
      connectTimeout: 100
      readTimeout: 100
      writeTimeout: 100
      retry: true
    pool:
      maxIdleConnections: 6
      keepAliveDurationNs: 6

# jwt
jwt:
  header: Authorization
  secret: abkfdsfooi0934.!
  expiration: 86400 # 1 day
  route:
    authentication:
      path: /api/login/phone_login
      refresh: /api/login/refresh

security:
  user:
    name: admin
    password: 123456
  basic:
    path: /mgt/**
    enabled: false

management:
  info:
    git:
      mode: full
  security:
    enabled: true
  context-path: /mgt
  add-application-context-header: false

# Mybatis配置
mybatis:
  mapper-locations: classpath*:/com/onlythinking/shop/**/*Mapper.xml
# Mybatis 分页
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: true
  supportMethodsArguments: true

# http request logging trace
logbook:
  exclude:
    - /mgt/**
  format:
    style: curl
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
  write:
    chunk-size: 1000

# API文档
apiDocs:
  title: API
  description: 接口API文档。
  version: 1.0
  author: Li Xingping
  url: 127.0.0.1:8300
  email: lixingping233@gmail.com
  restData: false
  basePackage: com.onlythinking.shop
